when:
  - event: manual

steps:
  - name: build
    image: gradle:7.6.6-jdk11
    commands:
      - ./gradlew build

  - name: containerise
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: zot.khuddam.org.uk
      repo: zot.khuddam.org.uk/hello-world
      dockerfile: Dockerfile
      context: .
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_API_TOKEN
      purge: true
